version: '3.9'

services:
  production:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.stage
    container_name: api
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=prod
      - MJ_EMAIL_FROM=gregoire.richard@hetic.net
      - MJ_EMAIL_NAME=Grégoire
      - MJ_APIKEY=6c3753626d9281a7710a60e0f93ed0d7
      - MJ_APISECRET=b58128225c25dbdd4fb75c08fb8e6e3d
      - FRONT_URL=https://main--classy-creponne-0128f0.netlify.app
      - PORT=5050
      - DB_HOST=dbms
      - DB_USER=produsr
      - DB_DATABASE=production
      - DB_PASSWORD=prodpswd
      - RSA_PRIVATE_KEY=/app/secrets/signing/ovh_vps
    networks:
      - api-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    
  dbms:
    image: mariadb
    restart: always
    ports:
      - "3309:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=M)8*=y2;WUD9sQ-&
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./dbms/dbms-data:/var/lib/mysql
      - ./dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
    name: api-network
